[package]
name = "utils"
authors.workspace = true
edition.workspace = true
version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
dotenvy = { workspace = true }
toml = { workspace = true }
get_fields = "0.1.0"
serde = { workspace = true }
syn = { version = "2.0", features = ["derive", "full"] }
quote = "1.0"
proc-macro2 = "1.0"
